version: '3.9'

services:
  nefis2nc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nefis2nc
    volumes:
      - ".:/app"
    working_dir: /app
    stdin_open: true  
    tty: true
    command: ["/bin/bash"]
#    command: ["python2.7", "trih2nc.py"]